Wf 111 push notifications backend
devLeaders/CodeTutorials pull request #74
Opened 2020-08-28 09:30 UTC by duch0416

2020-08-28 10:22 UTC, Adamwojty requested changes

2020-08-28 10:22 UTC, Adamwojty commented on packages/backend/src/notifications/notifications.service.ts
> +    console.log(res);
console.log

2020-08-28 10:22 UTC, Adamwojty commented on packages/backend/src/notifications/notifications.service.ts
> +  data?: any;
czemu any?

2020-08-28 10:41 UTC, duch0416 commented on packages/backend/src/notifications/notifications.service.ts
> +  data?: any;
bo jeszcze nie wiadomo jakei typu bedą zwracane dane

2020-08-31 03:29 UTC, dkolenda commented
:(

2020-08-31 13:43 UTC, JustynaKolenda commented on packages/backend/src/notifications/firebaseConfiggg.json
> +  "type": "service_account",
tez tak uwazam, zeby to byly envy

2020-08-31 13:53 UTC, JustynaKolenda approved these changes
ok

2020-09-04 09:54 UTC, closed without merging