Wf 101 mobile qr code videos
devLeaders/CodeTutorials pull request #80
Opened 2020-09-11 07:48 UTC by JustynaKolenda

2020-09-11 09:56 UTC, duch0416 requested changes

2020-09-11 09:56 UTC, duch0416 commented on packages/mobile/App.tsx
> +    fetch(new Request(url, {redirect: 'manual'})).then((res)=>{
zostawiłaś consol logi

2020-09-11 09:56 UTC, duch0416 commented on packages/mobile/src/features/common/components/NavOption.tsx
> +    static optionsQrcode= () => {
ten plik zaczyna robić się duży może jest jakiś sposób żeby ten kod troche podzielić

2020-09-11 09:56 UTC, duch0416 commented on packages/mobile/src/config/routing/QrScaner.tsx
> +        const cos = url.substring(test,url.length)
nazwa zmiennej do zmiany

2020-09-11 09:56 UTC, duch0416 commented on packages/mobile/src/config/routing/QrScaner.tsx
> +        console.log(parsed.v)
consol log

2020-09-11 09:56 UTC, duch0416 commented on packages/mobile/src/config/routing/QrScaner.tsx
> +            console.log(res.url);
consol log i typ playera możnaby było wrzucić do enuma

2020-09-11 10:09 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/QrScaner.tsx
> +        console.log(parsed.v)
ok

2020-09-11 10:10 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/QrScaner.tsx
> +        const cos = url.substring(test,url.length)
a fakt zapomiałam sobie ich zmienic :)

2020-09-11 10:22 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/QrScaner.tsx
> +            console.log(res.url);
ok

2020-09-11 10:22 UTC, JustynaKolenda commented on packages/mobile/App.tsx
> +    fetch(new Request(url, {redirect: 'manual'})).then((res)=>{
ok

2020-09-13 11:13 UTC, JustynaKolenda reviewed
:(

2020-09-13 11:14 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/QrScaner.tsx
> +export class ScanScreen extends Component <ScanScreenP> {
nie :)

2020-09-13 19:20 UTC, closed without merging