Wf 97 backend reset password request
devLeaders/CodeTutorials pull request #84
Opened 2020-09-22 20:10 UTC by jash90

2020-09-23 07:54 UTC, JustynaKolenda commented on packages/backend/src/auth/auth.service.ts
> +      Cześć, niedawno otrzymaliśmy od Ciebie prośbę o zresetowanie hasła do tego konta My Netflix. </br>
juz nie my Netflix tylko CodeTutorials

2020-09-23 08:26 UTC, JustynaKolenda commented on packages/backend/src/auth/auth.service.ts
> +      return { message: 'Email send.', jwtToken };
a te message moze mógłbyś do enuma wrzucić ?

2020-09-23 08:28 UTC, JustynaKolenda requested changes
mam jeszcze takie dwie małe uwagi :)

2020-09-23 08:55 UTC, dkolenda requested changes
:(

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/token/token.module.ts
> +import {Module} from "@nestjs/common";
jak to osobny modul to wyciagnij go z katalogu auth - ja bym go wcielil w modul auth

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/auth.service.ts
> +      if (changePasswordDTO.password !== changePasswordDTO.repeatPassword) {
ta walidacja chyba nie potrzebna po twojej stronie

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/auth.service.ts
> +      return {message: 'Password changed.'};
do enum

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/auth.service.ts
> +        html: `<h1>
tresc maila do osobnego pliku (to co podstawiasz do html:)

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/changePassword.dto.ts
> +	repeatPassword: string;
tego nie potrzebujesz

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/changePassword.dto.ts
> +	@MinLength(8)
długość trzymaj w jakiejs stałej by była wspólna z UserDTO by wykluczyc awarie gdy w UserDTO zmieni się długość a tu nie

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/jwttoken.dto.ts
> +export class JWTTokenDTO implements IJWTTokenRequest {
DTO to pattern do komunikacji z zewnetrznymi tworami nie musi sie tak nazywac kady model

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/jwttoken.dto.ts
> +    @ApiProperty()
czemu to ma takie dekorator? który controler oczekuje tego modelu?

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/auth/token.dto.ts
> +export class TokenDTO implements ITokenRequest {
który kontroler oczekuje tego modelu?

2020-09-23 08:55 UTC, dkolenda commented on packages/backend/src/migration/1600707228300-tokens.ts
> +export class tokens1600707228300 implements MigrationInterface {
jak sie ma device do tokens?

2020-09-23 08:55 UTC, dkolenda commented on packages/common/features/auth/models/index.d.ts
> +export interface IResetPasswordRequest {
gdzie src do tego?

2020-09-23 08:55 UTC, dkolenda requested changes
:(

2020-09-24 17:48 UTC, Adamwojty requested changes

2020-09-24 17:48 UTC, Adamwojty commented on packages/backend/src/auth/auth.service.ts
> +        to: "bartekziimny90@gmail.com",
tu chyba powinien być email użytkownika

2020-09-24 18:46 UTC, closed without merging