Wf 122 req login singup
devLeaders/CodeTutorials pull request #87
Opened 2020-09-30 16:39 UTC by JustynaKolenda

Sporo bugów poprawiłam na mobilce i nie ma już żadnych warningów :D  dodatkowo dodałam reqesty z  backendu wiec zdjecia na slaiderach są z bazy, logowanie też jest tu poprawione i pare rzeczy na backendzie

2020-10-01 18:41 UTC, duch0416 approved these changes

2020-10-02 09:02 UTC, Adamwojty approved these changes

2020-10-03 12:15 UTC, dkolenda requested changes
:(

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/common/components/NavOption.tsx
> +    // static optionsSingleMovie = () => {
do wylotu?

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +      {(this.props.id != null)?
zawsze powinnas miec id i odpowiedzialnoscia komponentu rodzica jest Ci go tu dostarczyc

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +                onPress= {()=> this.props.navigation.navigate(NavigationName.MENU)}
funkcja strzalkowa

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +                onPress= {()=>this.props.navigation.navigate(NavigationName.MENU)}
jw

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/FiltersScreen.tsx
>  const Wrapper = styled.ScrollView({
daj style pod komponent bo trza strasznie dlugo scrollowac zanim dojade do gownego elementu w pliku

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +  const [listVideos, setListVideos] = useState<Array<IVideosRespons>>([])
może osony hook?

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +              ListHeaderComponent= {
zawarunkował bym wyswietlanie MainScreenHeader zamiast sprawdzac w srodku cz id jest nul

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +          <FlatList
mozna by zawarunkowac cala flatlist i zamiast niej dopuki nie mamy filmow niezbednych do działania wyswietlac jakis kreciolek

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +  const navigationOptions = {
co to?

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +  const [ video, setVideo] = useState<IVideosRespons>()
do osobnego hooka

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +  const [ video, setVideo] = useState<IVideosRespons>()
spróbujmy zastosowac viewmodel

2020-10-03 12:15 UTC, dkolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +            <MainScreenHeader id={video?.id} idYoutube={video?.idYoutube} urlPhoto={video?.urlPhoto}  navigation={navigation}/>
zaifowal bym wyswietlanie całej zawartosci ekranu dopuki nie mamy niezbednych rzeczy

2020-10-14 16:03 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +            <MainScreenHeader id={video?.id} idYoutube={video?.idYoutube} urlPhoto={video?.urlPhoto}  navigation={navigation}/>
oki w sumie racja

2020-10-14 16:37 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +          <FlatList
a no racja

2020-10-14 16:44 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +              ListHeaderComponent= {
chyba jest już ok

2020-10-14 16:46 UTC, JustynaKolenda commented on packages/mobile/android/app/build.gradle
> +    // implementation project(path: ":@react-native-firebase_app")
ok

2020-10-14 16:46 UTC, JustynaKolenda commented on packages/mobile/android/settings.gradle
> +// include ':@react-native-firebase_app'
ok

2020-10-14 16:58 UTC, JustynaKolenda commented on packages/mobile/src/config/axios/axiosInit.tsx
> +    //AxiosInstance.defaults.headers.Authorization =  `Bearer ${await AsyncStorage.getItem("token")}`;
ok

2020-10-14 21:16 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +      {(this.props.id != null)?
ok

2020-10-14 21:29 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +                onPress= {()=> this.props.navigation.navigate(NavigationName.MENU)}
ok

2020-10-14 21:29 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/components/MainScreen/MainScreenHeader.tsx
> +                onPress= {()=>this.props.navigation.navigate(NavigationName.MENU)}
ok

2020-10-14 21:30 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/FiltersScreen.tsx
>  const Wrapper = styled.ScrollView({
ok

2020-10-14 21:38 UTC, JustynaKolenda commented on packages/common/features/auth/connectors/index.d.ts
>  import { AxiosPromise } from "axios";
ok

2020-10-14 21:40 UTC, JustynaKolenda commented on packages/backend/src/videos/videos.service.ts
> +			console.log(e);
ok

2020-10-15 11:23 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/DrawerNav/ProfileBox.tsx
> +                        onPress={() => removeToken()}>
poprawione , zrobiłam z tego hooka

2020-10-15 11:46 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/DrawerNav/DrawerContentScreen.tsx
> +    useEffect(()=>{
ok

2020-10-15 11:56 UTC, JustynaKolenda commented on packages/mobile/src/config/routing/BottomNavigation/FooterButton.tsx
> +    const onPress = () => {
ok

2020-10-15 15:14 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/MoviesList.tsx
> +  const [listVideos, setListVideos] = useState<Array<IVideosRespons>>([])
ok

2020-10-15 15:40 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +  const navigationOptions = {
a to chwilowo było

2020-10-15 15:42 UTC, JustynaKolenda commented on packages/mobile/src/features/common/components/NavOption.tsx
> +    // static optionsSingleMovie = () => {
nie, do poprawy

2020-10-15 17:31 UTC, JustynaKolenda commented on packages/mobile/src/features/videos/page/SingleMovie.tsx
> +  const [ video, setVideo] = useState<IVideosRespons>()
ok

2020-10-17 16:33 UTC, closed without merging